name: Documentation


on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Build documentation
      run: |
        pip install poetry
        poetry install
        mkdir site
        touch site/.nojekyll
        poetry run mkdocs build

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: site
